[project]
name = "incolume.py.utils"
version = "3.1.0a3"
description = "package incolume.py.utils"
readme = "README.md"
keywords = ['python', 'utils', 'incolume']
requires-python = ">=3.9,<4"
classifiers = [
  'Development Status :: 5 - Production/Stable',
  'Operating System :: OS Independent',
  'Natural Language :: Portuguese (Brazilian)',
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  'Topic :: Software Development :: Libraries :: Python Modules',
  'Topic :: Utilities',
]
dependencies = [
    "click>=8.1.5",
    "deprecated>=1.2.18",
    "rstr>=3.2.2",
    "tomli; python_full_version < '3.11'",
    "tqdm",
]

[dependency-groups]
dev = [
    "incolume-py-changelog>=0.8.0 ; python_full_version >= '3.9'",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "pytest-cov>=5.0.0",
    "pytest-mock>=3.14.1",
    "ruff>=0.12.12",
    "taskipy>=1.14.1",
    "tox>=4.25.0",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.18",
    "mkdocs-static-i18n>=1.3.0",
    "mkdocstrings>=0.30.0",
    "mkdocstrings-python>=1.18.2",
]
sec = [
    "bandit>=1.8.6",
    "safety>=3.6.1",
]

[tool.poetry.urls]
'Documentation' = ''
'Source' = 'https://github.com/development-incolume/incolume.py.utils'
'Git' = 'https://github.com/development-incolume/incolume.py.utils.git'
'Tracker' = 'https://github.com/development-incolume/incolume.py.utils/issues'
'Oficial' = 'https://pypi.org/project/incolume.py.utils/'

[project.scripts]
incolumepy-utils = 'incolume.py.utils.main:run'
pw = 'incolume.py.utils.cli:encode'

[tool.poetry]
name = "incolumepy.utils"
version = "3.0.0a3"
description = "package incolume.py.utils"
keywords = ['python', 'utils', 'incolume']
authors = ["britodfbr <contato@incolume.com.br>"]
homepage = "https://pypi.org/project/incolumepy.utils"
repository = 'https://gitlab.com/development-incolume/incolumepy.utils'
packages = [
  {include = "incolume", from=""},
]
include = [
  'README.md',
  "CHANGELOG.md",
  "docs/CHANGES.rst",
  'docs/HISTORY.rst',
  'docs/EXAMPLES.rst',
  'docs/CONTRIBUTORS.rst',
  'pyproject.toml',
]
exclude = [
  "examples/",
  "ez_setup",
  "incolumepy/utils/tmp",
  "my_package/excluded.py",
  "tests/",
]

[tool.poetry.dependencies]
python = "^3.9"
Deprecated = "^1.2.10"
rstr = "^2.2.6"
toml = {extras = ["tomli"], version = "^0.10.2"}
click = "^8.1.5"

[tool.poetry.group.dev.dependencies]
taskipy = "^1.12.0"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.0"
safety = "^2.2.0"
tox = "^3.20.1"

[tool.poetry.group.docs.dependencies]
myst-parser = "^0.16"
mkdocs = "^1.5.3"
mkdocs-material = "^9.4.5"

[tool.poetry.group.qa.dependencies]
mypy = "^0.931"
types-Deprecated = "^1.2.5"
types-toml = "^0.10.3"
ruff = "^0.0.292"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_format = '%(asctime)s; %(levelname)-8s; %(name)s; %(module)s; %(funcName)s; %(message)s'
log_date_format ='%Y-%m-%dT%H:%M:%S%z'
addopts = "--doctest-modules --cov=incolume -sx --cov-report term-missing --cov-report html:coverage_report/html --cov-report xml:coverage_report/cov.xml"
testpaths = [
  "tests",
]
markers = [
  "slow: marks tests as slow (deselect with '-m \"not slow\"')",
  "webtest: marks tests as webtest (deselect with '-m \"not webtest\"')",
  "fasttest: marks tests as fasttest (deselect with '-m \"not fasttest\"')",
]

[tool.coverage.html]
directory = "coverage_report/html"

[tool.coverage.xml]

[tool.coverage.run]
omit = [
  # omit anything in a .local directory anywhere
  "*/.local/*",
  # omit everything in /usr
  "/usr/*",
  # omit this single file
  "configure/truncus.py",
]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "if __name__ == .__main__.:",
  "logger.debug",
  "logger.info",
  "logger.warning",
  "logger.error",
  "except ImportError",
  "except (ModuleNotFoundError, ImportError)",
  "except ModuleNotFoundError",
  "__package__ =",
  "raise NotImplementedError",
  "def run",
  "def terminal.",
  "__author__",
  "class IElements"
]


[PEP8]
# Detalhes em https://pep8.org/
# define para todos os linters compatíveis
max-line-length = 79

[tool.black]
line-length = 79
#target-version = ['py39']
# include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/pyproject.toml  # exclude a file named pyproject.toml in the root of the project (in addition to the defaults)
\.tox
\.eggs
build
dist
exemplos
relatorios
docs
data
.pytest_cache
'''

[flake8]
#max-line-length = 120
max-complexity = 5

[tool.pylama]
format = "pylint"
skip = "*/.tox/*,*/.env/*"
linters = "pylint,mccabe"
ignore = "F0401,C0111,E731"

#[[tools.pylama.files]]
#path = "incolumepy/utils/files.py"
#ignore = "C901"
#skip = 1

[tool.pylama.linter.pyflakes]
builtins = "_"

[tool.pylama.linter.pycodestyle]
max_line_length = 79

[tool.pylama.linter.pylint]
max_line_length = 79
disable = "R"

[tool.pylama.linter.mccabe]
max-complexity=5

[tool.pylint.master]
init-hook = 'import sys; sys.path.append(".")'    # força carregamento do PYTHONPATH no pylint. Necessário no Windows.

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 79
# Format style used to check logging format string. `old` means using %
# formatting, `new` is for `{}` formatting,and `fstr` is for f-strings.
logging-format-style = 'old'

[tool.pylint.basic]
# Allow shorter and longer variable names than the default.
argument-rgx = "[a-z_][a-z0-9_]*$"
attr-rgx = "[a-z_][a-z0-9_]*$"
variable-rgx = "[a-z_][a-z0-9_]*$"

# Ensure that orjson is analysed as a C extension by pylint.
extension-pkg-whitelist = "orjson"

[tool.pylint.messages_control]
disable = [
    # Disable too many and too few checks.
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-boolean-expressions",
    "too-many-branches",
    "too-many-function-args",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-nested-blocks",
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-statements",
    "too-few-public-methods",

    # Similar lines in files (often the case in tests).
    "duplicate-code",

    # Many functions (e.g. callbacks) will naturally have unused arguments.
    "unused-argument",

    # Disable checking that method could be a function in classes (often used for organisation).
    "no-self-use",

    # Disable failure for TODO items in the codebase (code will always have TODOs).
    "fixme",

    # Disable docstrings checks as we don't require excessive documentation.
    "missing-docstring",

    "no-member",
    "unspecified-encoding",
]

[tool.mypy]
mypy_path = "incolumepy"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.isort]
multi_line_output = 3
#line_length = 120
include_trailing_comma = true

[pycodestyle]

#max_line_length = 120

# Fail
# TODO verificar disponibilidade no futuro; não funciona com pyproject.toml
#[pylava]
#format = 'pylint'
#async = 1
## ignore = D203,D213,F0401,C0111,E731,I0011
## linters = pycodestyle,pyflakes,mccabe,pydocstyle,pylint
#paths = ['src']
## skip = pylava/inirama.py,pylava/libs/*
#verbose = 0

[tool.ruff]
# Always generate Python compatible code.
target-version = "py39"
# Decrease the maximum line length to 79 characters.
line-length = 79
tab-size = 4
src = ["incolume/", "tests/"]
respect-gitignore = true
select = [
  "A",    #flake8-builtins
  "AIR",    #Airflow
  "ANN",    #flake8-annotations
  "ARG",    #flake8-unused-arguments
  "ASYNC",    #flake8-async
  "B",    #flake8-bugbear
  "BLE",    #flake8-blind-except
  "C4",    #flake8-comprehensions
  "C90",    #mccabe
  "COM",    #flake8-commas
  "CPY",    #flake8-copyright
  "D",   # pydocstyle
  "DJ",    #flake8-django
  "DTZ",    #flake8-datetimez
  "E",   # pycodestyle
  "W",    #pycodestyle
  "EM",    #flake8-errmsg
  "ERA",    #eradicate
  "EXE",    #flake8-executable
  "F",   # pyflakes
  "FA",    #flake8-future-annotations
  "FBT",    #flake8-boolean-trap
  "FIX",    #flake8-fixme
  "FLY",    #flynt
  "FURB",    #refurb
  "G",    #flake8-logging-format
  "I",    #isort
  "ICN",    #flake8-import-conventions
  "INP",    #flake8-no-pep420
  "INT",    #flake8-gettext
  "ISC",    #flake8-implicit-str-concat
  "N",    #pep8-naming
  "NPY",    #NumPy-specific rules
  "PD",    #pandas-vet
  "PERF",    #Perflint
  "PGH",    #pygrep-hooks
  "PIE",    #flake8-pie
  "PL",    #Pylint
  "PT",    #flake8-pytest-style
  "PTH",    #flake8-use-pathlib
  "PYI",    #flake8-pyi
  "Q",    #flake8-quotes
  "RET",    #flake8-return
  "RSE",    #flake8-raise
  "RUF",    #Ruff-specific rules
  "S",    #flake8-bandit
  "SIM",    #flake8-simplify
  "SLF",    #flake8-self
  "SLOT",    #flake8-slots
  "T10",    #flake8-debugger
  "T20",    #flake8-print
  "TCH",    #flake8-type-checking
  "TD",    #flake8-todos
  "TID",    #flake8-tidy-imports
  "TRY",    #tryceratops
  "UP",  # pyupgrade
  "YTT",    #flake8-2020
]

# Never enforce `E501` (line length violations).
ignore = ["INP001", "CPY001"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

[tool.ruff.per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
#"__init__.py" = ["E402"]
#"path/to/file.py" = ["E402"]
"**/{tests,docs,tools,utils}/*" = ["EXE002"]
"**/test_*.py" = [
  "I001",
  "EXE002",
  "ANN001",
  "ANN101",
  "PLR6301",
  "S101",
#  TODO remover ANN001 ANN201 ANN202 D100 D103 D202 PT007 após estabilizar teste piloto
#  TODO remover temporários no futuro
#  "ANN201",
#  "ANN202",
#  "D100",
#  "D103",
#  "D202",
#  "PT007",
]

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 5

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.flake8-quotes]
docstring-quotes = "double"    # ""single"
inline-quotes = "single"
multiline-quotes = "double"

[tool.taskipy.variables]
path = "incolume/ tests/"
CHANGELOGFILE = "docs/about/CHANGELOG.md"
URLCOMPARE = "https://github.com/development-incolume/incolume.py.utils/compare"

[tool.taskipy.tasks]
bandit={help='', cmd='poetry run bandit -c pyproject.toml -r {path}', use_vars=true}
pre_check-all = {cmd='echo Starting Check all ..', help=''}
check-all = {cmd='poetry run task clean-all; poetry run task lint; poetry run task sec',  help = "Checking all" }
post_check-all = {cmd='echo Checking finished!', help=''}
pre_docs-build={help='Pre docs-build', cmd="poetry run task changelog"}
docs-build = {help="Generate documentation", cmd="poetry run mkdocs gh-deploy --config-file mkdocs.yml --remote-branch webdoc"}
docs-serve = {help="Run server documentation", cmd="poetry run mkdocs serve"}
safety={help='Check safety of packages into project.', cmd='poetry run safety check'}
pre_sec={help='Securance validations', cmd='poetry run task bandit && poetry run task safety'}
sec={help="Checking environment's safety", cmd=''}
pre_changelog='poetry run pytest -m fast'
changelog = {help='Update changelog file', cmd = "poetry run gcl {CHANGELOGFILE} -u {URLCOMPARE} && echo CHANGELOG file - {CHANGELOGFILE} - updated with success.;echo", use_vars = true }
xpto = { cmd = "echo {path} {CHANGELOGFILE} {URLCOMPARE}", use_vars = true }
setup = { help = 'Configure environment develop', cmd='git config core.hooksPath .git-hooks/'}
